Repository input-output-hk/cardano-rosetta, pull requests merged in 2020-09, with the labels that each got.

#160 Correct Rosetta reference in README
  README.md
Labels: documentation

#154 Ci/rosetta-cli checks
  .github/actions/build_cardano_rosetta/action.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  README.md
  docs/QA.md
  test/check/README.md
  test/check/configuration/.gitignore
  test/check/configuration/src/base.json
  test/check/configuration/src/construction/1.json
  test/check/configuration/src/data/byron_sample.json
  test/check/configuration/src/data/shelley_sample.json
  test/check/configuration/src/data/shelley_transition_sample.json
  test/check/configuration/src/host/localhost.json
  test/check/configuration/src/network/mainnet.json
  test/check/configuration/src/network/testnet.json
Labels: DevOps, test

#162 docs: Readme fixes
  README.md
Labels: documentation

#164 Docker Hub Continuous Deployment + Manual dispatched pre-release workflow
  .github/actions/build_cardano_rosetta/action.yml
  .github/actions/smoke_test_cardano_rosetta/action.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/post_integration.yml
  .github/workflows/post_release.yml
  .github/workflows/pre_release.yml
  docs/MAINTAINER.md
Labels: DevOps

#167 Fix/workflow syntax
  .github/actions/build_cardano_rosetta/action.yml
  .github/actions/smoke_test_cardano_rosetta/action.yml
  .github/workflows/post_integration.yml
  .github/workflows/post_release.yml
  .github/workflows/pre_release.yml
  docs/QA.md
Labels: DevOps

#168 ci: fix tagging to use scope
  .github/workflows/post_integration.yml
  .github/workflows/post_release.yml
Labels: DevOps

#171 refactor: hoist Docker build context concerns + fix: missing ecosystem config
  .github/actions/build_cardano_rosetta/action.yml
  .github/actions/smoke_test_cardano_rosetta/action.yml
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  .github/workflows/post_integration.yml
  .github/workflows/post_release.yml
  .github/workflows/pre_release.yml
  Dockerfile
  README.md
  cardano-rosetta-server/README.md
  cardano-rosetta-server/docker-compose.yml
  config/ecosystem.config.js
  dev.Dockerfile
  scripts/build_dev_docker_images.sh
Labels: BUG, DevOps, PRIORITY:HIGH, SEVERITY:HIGH, chore

#172 ci: Updates to rosetta-cli v0.5.0
  .github/workflows/nightly.yml
  test/check/configuration/src/data/compat_patch.json
Labels: DevOps

#173 ci: fix build context in post-release workflow
  .github/workflows/post_release.yml
Labels: BUG, SEVERITY:LOW

#175 fix: account total balance was calculated using Number instead of BigInt
  cardano-rosetta-server/src/server/controllers/account-controller.ts
  cardano-rosetta-server/src/server/utils/data-mapper.ts
  cardano-rosetta-server/test/unit/utils/data-mapper.test.ts
Labels: BUG, PRIORITY:HIGH, SEVERITY:HIGH

#177 chore: fixed all linter warnings
  cardano-rosetta-server/src/server/controllers/block-controller.ts
  cardano-rosetta-server/src/server/controllers/controllers.ts
  cardano-rosetta-server/src/server/db/blockchain-repository.ts
  cardano-rosetta-server/src/server/db/network-repository.ts
  cardano-rosetta-server/src/server/db/queries/network-queries.ts
  cardano-rosetta-server/src/server/services/cardano-services.ts
  cardano-rosetta-server/src/server/services/services.ts
  cardano-rosetta-server/test/e2e/construction/construction-combine-api.test.ts
  cardano-rosetta-server/test/e2e/construction/construction-derive-api.test.ts
  cardano-rosetta-server/test/e2e/construction/construction-submit-api.test.ts
  cardano-rosetta-server/test/e2e/construction/cosntruction-payloads-api.test.ts
  cardano-rosetta-server/test/e2e/environment-parser.test.ts
  cardano-rosetta-server/test/e2e/fixture-data.ts
  cardano-rosetta-server/test/e2e/network/netowork-status-api.test.ts
  cardano-rosetta-server/test/e2e/network/network-list-api.test.ts
  cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
  cardano-rosetta-server/test/e2e/server/server.test.ts
Labels: SEVERITY:LOW, chore

#174 ci: fix check data configuration to remove compat_patch
  .github/workflows/nightly.yml
  test/check/README.md
  test/check/configuration/src/construction/host/localhost.json
  test/check/configuration/src/data/compat_patch.json
  test/check/configuration/src/data/host/localhost.json
Labels: chore

#176 Feature/docker runtime config
  Dockerfile
  README.md
  cardano-rosetta-server/README.md
  config/ecosystem.config.js
Labels: enhancement

#178 fix: dont ask for socket file to exist when parsing env
  cardano-rosetta-server/src/server/utils/environment-parser.ts
Labels: BUG, DevOps, SEVERITY:HIGH

#182 Docs/specify shm size in run
  .github/actions/smoke_test_cardano_rosetta/action.yml
  .github/workflows/nightly.yml
  README.md
Labels: BUG
