Repository input-output-hk/cardano-rosetta, pull requests merged in 2020-12, with the labels that each got.

#223 fix: there were missing some staking network operations
  cardano-rosetta-server/src/server/controllers/network-controller.ts
  cardano-rosetta-server/src/server/utils/constants.ts
  cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
Labels: BUG

#233 chore: update check configuration for rosetta-cli@0.6.2
  test/check/.gitignore
  test/check/README.md
  test/check/configuration/construction/configuration.json
Labels: chore

#241 fix: networkId wasn't properly checked after #238
  cardano-rosetta-server/src/server/controllers/account-controller.ts
  cardano-rosetta-server/src/server/controllers/block-controller.ts
  cardano-rosetta-server/src/server/controllers/construction-controller.ts
  cardano-rosetta-server/src/server/controllers/controllers-helper.ts
  cardano-rosetta-server/src/server/controllers/controllers.ts
  cardano-rosetta-server/src/server/controllers/network-controller.ts
  cardano-rosetta-server/test/e2e/block/block-api.test.ts
  cardano-rosetta-server/test/unit/services/netowork-service.test.ts
Labels: BUG, PRIORITY:HIGH, SEVERITY:HIGH

#159 chore: 14 - finalize documentation
  README.md
  cardano-rosetta-server/README.md
  docs/rosetta-custom-definitions.md
  docs/staking-support.md
  examples/README.md
Labels: documentation

#246 test: coverage increase for cardano service related endpoints
  cardano-rosetta-server/src/server/services/cardano-services.ts
  cardano-rosetta-server/test/e2e/construction/construction-payloads-api.test.ts
Labels: test

#254 docs: tests snapshot generation explanation
  cardano-rosetta-server/README.md
Labels: documentation

#251 Feat/updated construction dsl for staking
  test/check/README.md
  test/check/configuration/construction/delegation-configuration.json
  test/check/workflows/delegation.ros
  test/check/workflows/transfer.ros
Labels: construction-api, enhancement
