Repository input-output-hk/cardano-rosetta, pull requests merged in 2020-08, with the labels that each got.

#143 feat: update cardano node version
  cardano-rosetta-server/src/server/controllers/network-controller.ts
  cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
Labels: chore

#144 fix: correct link to raw Dockerfile, use master until next release
  Dockerfile
  README.md
Labels: BUG, SEVERITY:MEDIUM

#111 [SRE-127] Setup nix CI
  default.nix
  nix/cardano-rosetta-server.nix
  nix/packages.nix
  nix/pkgs.nix
  nix/sources.json
  nix/sources.nix
  release.nix
  shell.nix
Labels: chore

#156 ci: Add data cache update workflow for use in CI
  .github/actions/build_cardano_rosetta/action.yml
  .github/workflows/update-data-cache.yml
Labels: DevOps

#157 ci: remove workflow in favour of continuous external node
  .github/workflows/update-data-cache.yml
Labels: DevOps

#158 fix: generic error handling
  cardano-rosetta-server/src/server/api-error.ts
  cardano-rosetta-server/src/server/server.ts
  cardano-rosetta-server/src/server/utils/errors.ts
  cardano-rosetta-server/test/e2e/network/network-options-api.test.ts
  cardano-rosetta-server/test/e2e/server/server.test.ts
Labels: BUG, SEVERITY:HIGH

#152 docs: correct --name argument and add context to volume name
  README.md
  cardano-rosetta-server/README.md
Labels: documentation
